### ISSUE TITLE
Adapter get incorrect test's method name, coz dataProvider

### ISSUE THREAD

**Issue by rothaarNatalia** [allure-framework/allure-phpunit#30]
If test uses dataProvider
Adapter get incorrect test's method name
http://screencast.com/t/DJRchcoc5x

**Comment by rothaarNatalia** [comment]
/**
     * Gets the name of a TestCase.
     *
     * @param  boolean $withDataSet
     * @return string
     */
    public function getName($withDataSet = true)
    {
        if ($withDataSet) {
            return $this->name . $this->getDataSetAsString(false);
        } else {
            return $this->name;
        }
    }

**Comment by vania-pooh** [comment]
@rothaarNatalia any thoughts how to fix this? Probably I'm using some incorrect call in my adapter class.

**Comment by rothaarNatalia** [comment]
SuiteName incorrect too. It helps me
Change in AllureAdapter.php 
public function startTest(PHPUnit_Framework_Test $test)
instead Annotation\AnnotationProvider::getMethodAnnotations($suiteName, $methodName)
to use Annotation\AnnotationProvider::getMethodAnnotations(get_class($test), $methodName)
Work with and without provider

But I've another issue
build\allure-results <-- here my tests result, I try to generate report using allure-cli
allure report generate absolutePath\build\allure-results

and received such error
http://screencast.com/t/8in665es
file with reports
https://yadi.sk/d/6uuPUJMSfwivv

**Comment by vania-pooh** [comment]
@Djamiyo any thoughts?

**Comment by Djamiyo** [comment]
@vania-pooh Ok, I'll try to figure out the reason tonight.

**Comment by Djamiyo** [comment]
It looks like we have some problems with design. Test suite, being started inside another one, overwrites it's uuid, so the parent suite could never be finished. If we can't have suite inside another suite in Allure report, I think we should look for suite in storage by name, then get uuid and fire events for appropriate one. So we would have 2 different suites in report. But the problem needs further discussion.

**Comment by vania-pooh** [comment]
@Djamiyo Allure does not support nested suites. We expect an unlimited list of suites with unlimited set of cases and steps inside.

**Comment by tyz910** [comment]
Fixed in #32. I think we can close it.
