### ISSUE TITLE
@Step annotation is not available

### ISSUE THREAD

**Issue by ostrovanka** [allure-framework/allure-phpunit#35]
Hi!
Just wanted to know if you are planning to implement @Step annotation  functionality like in java for phpunit adapter?
Existing mechanism of markings step in phpunit is very inconvenient.

Please, tell me if you planning to update this any time soon?

Thank you!

**Comment by cryptton2004** [comment]
I don't know if it's of any help, but I found a workaround to manage test steps in my test cases.
The setup file contains this:
```
    use StepSupport;

    public $stepCounter = 0;
    /**
     * @param $command
     * 'The selenium command to be used'
     * @param $title
     * 'The name or title of the step (will be displayed in the report')
     */
    public function executeTestStep($command, $title) {
        $stepCounter = $this->stepCounter;
        $stepCounter++;
        $this->stepCounter = $stepCounter;
        $step = $command;
        $stepName = "step".$stepCounter;
        if(is_array($step)){
            foreach($step as $stepValue){
                $stepTitle = $title;
                $this->executeStep($stepName,$stepValue, $stepTitle);
            }
        }
        else{
            $stepTitle = $title;
            $this->executeStep($stepName,$step, $stepTitle);
        }

    }
```

And the actual test steps look something like:

```
        $step = $this->click("link=Add a Client");
        $stepTitle = "After the page loads, click on the 'Add a Client' button";
        $this->executeTestStep($step,$stepTitle);

        $step = $this->waitForPageToLoad("30000");
        $stepTitle = "Wait for the page to load";
        $this->executeTestStep($step,$stepTitle);
```

At the end, the generated report converts nicely to an allure HTML report with steps.

**Comment by ostrovanka** [comment]
@cryptton2004 Thank you for your code. I've used it in my project - it really looks nice in allure reports, but the code itself unfortunately looks not so nice :( But I guess it's the situation where you have to choose - pretty code or pretty report :)

**Comment by cryptton2004** [comment]
I don't know how others people code looks like (mine is really messy), but I found out that this workaround forces me to 'comment' my steps so that anyone can understand it. It looks like a wall of text now, but at least inexperienced people get an idea of what's going on there.
