### ISSUE TITLE
Tests with Exceptions are marked as broken

### ISSUE THREAD

**Issue by techhemant** [allure-framework/allure-phpunit#45]
Status of a failing test is marked as broken by this adapter in the xmls under allure-results. Which results in test shown as broken instead of failed in the report.

I'm using "allure-framework/allure-phpunit": "1.3.0" and allure command line version 2.13.0

<img width="749" alt="Screen Shot 2019-11-07 at 1 28 43 pm" src="https://user-images.githubusercontent.com/41311719/68355314-f78f2e00-0162-11ea-9241-d43788e590e3.png">

<img width="1535" alt="Screen Shot 2019-11-07 at 1 25 14 pm" src="https://user-images.githubusercontent.com/41311719/68355053-29ec5b80-0162-11ea-91d5-22d373f85932.png">

**Comment by eduard-sukharev** [comment]
One should not throw exceptions to *fail* a test, but rather use special asserting tools to either check results of test, or expect an exception (thus, catching it but not allowing test suite to fail due to unhandled test exception).
Some code would help to clarify, though.

**Comment by techhemant** [comment]
You're right. Perhaps, we're passing custom exception in parent::onNotSuccessfulTest($newException); is causing test to appear broken instead of failed. 

We use
public function onNotSuccessfulTest(Throwable $e){
        // Add the test re-run command to the test error message
        $newException = new \Exception(
            $e->getMessage()
            . "\n" . $e->getTraceAsString(),
            0
        );
parent::onNotSuccessfulTest($newException);
}

**Comment by techhemant** [comment]
It seems this was the issue with my framework code. Closing the issue.
