### ISSUE TITLE
PHPUnit warnings aren't treated as failures in Allure reports

### ISSUE THREAD

**Issue by slavvka** [allure-framework/allure-phpunit#47]
PHPUnit warnings aren't treated as failures in Allure reports. They are just ignored whereas PHPUnit fails with exitcode 1.

https://github.com/allure-framework/allure-phpunit/blob/master/src/Yandex/Allure/PhpUnit/AllurePhpUnit.php#L107-L110

**Comment by baev** [comment]
fixed via #48 , released in 1.5.0
