### ISSUE TITLE
Class 'Yandex\Allure\Adapter\Model\Provider' not found

### ISSUE THREAD

**Issue by biechao** [allure-framework/allure-phpunit#49]
When I run phpunit, I got this error message:

Class 'Yandex\Allure\Adapter\Model\Provider' not found in 'xx/xx/vendor/vendor/allure-framework/allure-phpunit/src/Yandex/Allure/Adapter/AllureAdapter.php'

Anybody know why?

**Comment by eduard-sukharev** [comment]
Looks like your vendor path is broken - it should probably be single `/vendor`, not `/vendor/vendor`. Check your path mappings in your phpunit configuration.
